apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul-demo
  labels:
    app: consul-demo
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: consul-demo
    spec:
      volumes:
        - name: config-output-volume
          emptyDir:
            medium: Memory
      initContainers:
        - name: consul-config-init
          image: gcr.io/acedemand-poc/consul-init:5
          env:
            - name: CONSUL_ADDR
              value: "http://consul-server.hashicorp:8500"
            - name: CONFIG_KEY_PATH
              value: /test/1/data
            - name: CONFIG_OUTPUT_FILEPATH
              value: /app/config/app-config.properties
          volumeMounts:
            - name: config-output-volume
              mountPath: /app/config
          imagePullPolicy: IfNotPresent
      containers:
        - name: application
          image: nginx
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: config-output-volume
              mountPath: /app/config
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      schedulerName: default-scheduler

